# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ocr(object):
    def setupUi(self, ocr):
        ocr.setObjectName("ocr")
        ocr.resize(400, 300)
        self.sel_imgfile = QtWidgets.QPushButton(ocr)
        self.sel_imgfile.setGeometry(QtCore.QRect(10, 10, 111, 31))
        self.sel_imgfile.setObjectName("sel_imgfile")
        self.sel_txtfile = QtWidgets.QPushButton(ocr)
        self.sel_txtfile.setGeometry(QtCore.QRect(10, 120, 111, 31))
        self.sel_txtfile.setObjectName("sel_txtfile")
        self.run = QtWidgets.QPushButton(ocr)
        self.run.setGeometry(QtCore.QRect(20, 230, 75, 23))
        self.run.setObjectName("run")
        self.over = QtWidgets.QPushButton(ocr)
        self.over.setGeometry(QtCore.QRect(290, 230, 75, 23))
        self.over.setObjectName("over")
        self.img_lineEdit = QtWidgets.QLineEdit(ocr)
        self.img_lineEdit.setGeometry(QtCore.QRect(20, 60, 361, 31))
        self.img_lineEdit.setObjectName("img_lineEdit")
        self.txt_lineEdit = QtWidgets.QLineEdit(ocr)
        self.txt_lineEdit.setGeometry(QtCore.QRect(20, 170, 361, 31))
        self.txt_lineEdit.setObjectName("txt_lineEdit")

        self.retranslateUi(ocr)
        QtCore.QMetaObject.connectSlotsByName(ocr)

    def retranslateUi(self, ocr):
        _translate = QtCore.QCoreApplication.translate
        ocr.setWindowTitle(_translate("ocr", "代码识别"))
        self.sel_imgfile.setText(_translate("ocr", "选择图片文件夹"))
        self.sel_txtfile.setText(_translate("ocr", "选择txt存放目录"))
        self.run.setText(_translate("ocr", "开始运行"))
        self.over.setText(_translate("ocr", "关闭程序"))
